### ISSUE TITLE
exception on proof processing

### ISSUE THREAD

**Issue by ASamSam** [pcarrott/pylspclient#64]
Hello

have exception working with oyur lib.
did try on fourcolor theorem - standard , coq 8.20

at the line 

>>Theorem four_color_finite m :   finite_simple_map m -> colorable_with 4 m.
(next line will be:
Proof.)

_in_proof_ already reports _True_
but _self.open_proofs_ is still [] at this moment

so 
_elif len(self.open_proofs) > 0 if undo else self.in_proof:_
result True and leads to Exception

<img width="691" height="282" alt="Image" src="https://github.com/user-attachments/assets/079caef5-31cd-4a00-b8e2-3555ea27bd83" />

**Comment by Nfsaavedra** [comment]
Hi!

How did you compile the fourcolors project? I saw that you opened an issue in that repository (https://github.com/rocq-community/fourcolor/issues/75) and I'm having the same problems.

After opening the `ProofFile` if you call the attribute `is_valid` does it return True?

**Comment by ASamSam** [comment]
Hello. As i understood, i do looking on the rpoof included into the package. the one downloaded directly from sources was nto workable.
i think i did somethign like
_opam install coq coq-fourcolor_

at least
opam list | grep fourcolor

gives me 

<img width="877" height="37" alt="Image" src="https://github.com/user-attachments/assets/f6cc60d9-f628-49e6-8a7c-c5c5aa15bcbf" />
-----------

i do open the 'fourcolor.v' with your library.
_is_valid_ tells **True**

do you think you can fix it soon?

**Comment by pcarrott** [comment]
Hi! I managed to run the file successfully by following these steps:

1. Install `coq-fourcolor` via opam (`opam install coq-fourcolor`)
2. Clone the `fourcolor` repository
3. Create a `ProofFile` with `theories/proof/fourcolor.v` from the repository (not opam) and the following arguments:
    - a timeout of 240 (8 times the default)
    - a memory limit of 4194304 (2 times the default)

A couple of things to note:

1. The memory limit is not customizable for `ProofFile`s, so I just opened a PR (#65) that allows that.
2. The run is very slow (40+ minutes I think). I assume it's related with the large amount of libraries that are imported by the file.
3. Although the file is from the repository, since the source code is not compiled, the libraries are being imported from the opam library.

If you reproduce these steps from scratch, do you still get the same error? I imagine the errors you are getting might be in some way related with timeouts/memory (or other coq-lsp related issues).

**Comment by ASamSam** [comment]
Thank you for your effort,
But I'm definitely missing something

I got your update, and able to define the memory_limit, but still facing the same problem.
Did try both ways:

<img width="692" height="46" alt="Image" src="https://github.com/user-attachments/assets/14140359-dc6f-42e3-8319-0111addb46ec" />


<img width="616" height="69" alt="Image" src="https://github.com/user-attachments/assets/20c626e1-c17c-4d03-8f10-0aba594aaf2e" />

and have the same issue:

<img width="742" height="400" alt="Image" src="https://github.com/user-attachments/assets/6174f63a-7477-4b58-855c-1c020e68227b" />

But your message gives me some optimism about the possibility of making it work!
Maybe i need to add paths to some libraries?

**Comment by pcarrott** [comment]
One last suggestion: have you tried running `make clean` in the repository before running the file? In my case, I didn't try to compile the repository because I knew compilation would crash. But I decided to compile it now and coq-lsp reports errors for both files (even though it seems they are not being sent to CoqPyt, which is making the file valid).

There might be some compatibility issues between the partly compiled repository and the opam library, so could you please check if you get the same error after cleaning the failed compilation?

**Comment by ASamSam** [comment]
I would really like to use your library!
Edit: sorry, just found that python 3.12 required and i have 3.10. updating

The four color I do use now is compilable (I'm not sure why, but maybe just everything is up-to-date)

'make clean' do not change anything

but i found that 'span' for each step loaded in your code seems meaningful for understanding the type of the node

<img width="1019" height="777" alt="Image" src="https://github.com/user-attachments/assets/baf797e0-abcf-4dbc-895c-b2453337a58e" />

and it is None everywhere...

so this test fails:

<img width="583" height="387" alt="Image" src="https://github.com/user-attachments/assets/ce9c6ddb-8f68-4ad6-ac8d-0a770840d1af" />


I do use Ubuntu if it makes a change..

**Comment by ASamSam** [comment]
well, it works in another way now.
not spending lot of time (15 seconds maybe)
it results empty proof list after processing fourcolor.v ...
but no errors
span is empty everywhere

**Comment by Nfsaavedra** [comment]
Can you tell us the result of running:
```
opam show coq-lsp
```
?

**Comment by ASamSam** [comment]
Here it is:
[coq-lsp.txt](https://github.com/user-attachments/files/23696808/coq-lsp.txt)

Could you please provide the exact call you used?
I`m not familiar with the lib yet )

**Comment by pcarrott** [comment]
There's the issue. CoqPyt is only compatible with coq-lsp 0.2.3, we do not support 0.2.4 yet. If you downgrade coq-lsp to 0.2.3+8.20, it should solve the issue.

**Comment by ASamSam** [comment]
thank you very much! going to try

**Comment by ASamSam** [comment]
definitely starts to work, thank you. 
Seems I missed this dependency during install 
On the first run, I encountered an exception due to a resource lock timeout; I then restarted. I think it is solvable with the timeout (i do use Ubuntu on VirtualBox, which can be slower)

**Comment by ASamSam** [comment]
[exception.txt](https://github.com/user-attachments/files/23697882/exception.txt)
retrying with cache enabled

**Comment by ASamSam** [comment]
With Ubuntu on a virtual machine with a big timeout, and even added a retry on the first exception, I still have a problem with resources.

so i switched to windows + WSL (ubuntu) from virtual box+ ubuntu
simple file from the proof works, i start to understand how to use the lib, but

fourcolor.v gives a new exception:

(coqpyt) root@DESKTOP-PHAK7RF:/src/as_coq# /venvs/coqpyt/bin/python /src/as_coq/coq_as.py
CoqPyt loaded from : /venvs/coqpyt/lib/python3.12/site-packages/coqpyt/__init__.py
Loaded ProofFile in 1.16 seconds.
Traceback (most recent call last):
  File "/src/as_coq/coq_as.py", line 244, in <module>
    main()
  File "/src/as_coq/coq_as.py", line 231, in main
    deps = extract_deps_for_file(vfile)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/as_coq/coq_as.py", line 82, in extract_deps_for_file
    pf.run()
  File "/venvs/coqpyt/lib/python3.12/site-packages/coqpyt/coq/base_file.py", line 556, in run
    return self.exec(len(self.steps) - self.steps_taken)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venvs/coqpyt/lib/python3.12/site-packages/coqpyt/coq/proof_file.py", line 929, in exec
    self.__step(step(), sign == -1)
  File "/venvs/coqpyt/lib/python3.12/site-packages/coqpyt/coq/proof_file.py", line 584, in __step
    self.__handle_end_proof(step, undo=undo)
  File "/venvs/coqpyt/lib/python3.12/site-packages/coqpyt/coq/proof_file.py", line 538, in __handle_end_proof
    open_proof = self.__open_proofs.pop(open_index)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Can you please tell me if you have an idea what is wrong this time?
realprop.v gives same exception. I would say - with the 'Lemma real_sup_ub E : Real.has_sup E -> Real.ub E (Real.sup E).'
and it is not about timeout


i did print error, if it gives a key. in realprop:

Lemma real_sup_ub E : Real.has_sup E -> Real.ub E (Real.sup E).
Proof. exact: (Real.sup_upper_bound R). Qed

--> Error: 'The reference Real.has_sup was not found in the current environment.'
so it comes from the Real.v...

----------
when i specify the 'workspace' it crashes in the same way, but later
i`ll try to recompile the fourcolor


ok, with all the setup problems i had i forgot to compile the proof. 
now seems everything works, but strangely unstable on windows WSL-ubuntu
yet seems ok on virtual box ubuntu
